require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssociationFeesController do

  # This should return the minimal set of attributes required to create a valid
  # AssociationFee. As you add validations to AssociationFee, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssociationFeesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all association_fees as @association_fees" do
      association_fee = AssociationFee.create! valid_attributes
      get :index, {}, valid_session
      assigns(:association_fees).should eq([association_fee])
    end
  end

  describe "GET show" do
    it "assigns the requested association_fee as @association_fee" do
      association_fee = AssociationFee.create! valid_attributes
      get :show, {:id => association_fee.to_param}, valid_session
      assigns(:association_fee).should eq(association_fee)
    end
  end

  describe "GET new" do
    it "assigns a new association_fee as @association_fee" do
      get :new, {}, valid_session
      assigns(:association_fee).should be_a_new(AssociationFee)
    end
  end

  describe "GET edit" do
    it "assigns the requested association_fee as @association_fee" do
      association_fee = AssociationFee.create! valid_attributes
      get :edit, {:id => association_fee.to_param}, valid_session
      assigns(:association_fee).should eq(association_fee)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssociationFee" do
        expect {
          post :create, {:association_fee => valid_attributes}, valid_session
        }.to change(AssociationFee, :count).by(1)
      end

      it "assigns a newly created association_fee as @association_fee" do
        post :create, {:association_fee => valid_attributes}, valid_session
        assigns(:association_fee).should be_a(AssociationFee)
        assigns(:association_fee).should be_persisted
      end

      it "redirects to the created association_fee" do
        post :create, {:association_fee => valid_attributes}, valid_session
        response.should redirect_to(AssociationFee.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved association_fee as @association_fee" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssociationFee.any_instance.stub(:save).and_return(false)
        post :create, {:association_fee => { "name" => "invalid value" }}, valid_session
        assigns(:association_fee).should be_a_new(AssociationFee)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssociationFee.any_instance.stub(:save).and_return(false)
        post :create, {:association_fee => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested association_fee" do
        association_fee = AssociationFee.create! valid_attributes
        # Assuming there are no other association_fees in the database, this
        # specifies that the AssociationFee created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssociationFee.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => association_fee.to_param, :association_fee => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested association_fee as @association_fee" do
        association_fee = AssociationFee.create! valid_attributes
        put :update, {:id => association_fee.to_param, :association_fee => valid_attributes}, valid_session
        assigns(:association_fee).should eq(association_fee)
      end

      it "redirects to the association_fee" do
        association_fee = AssociationFee.create! valid_attributes
        put :update, {:id => association_fee.to_param, :association_fee => valid_attributes}, valid_session
        response.should redirect_to(association_fee)
      end
    end

    describe "with invalid params" do
      it "assigns the association_fee as @association_fee" do
        association_fee = AssociationFee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssociationFee.any_instance.stub(:save).and_return(false)
        put :update, {:id => association_fee.to_param, :association_fee => { "name" => "invalid value" }}, valid_session
        assigns(:association_fee).should eq(association_fee)
      end

      it "re-renders the 'edit' template" do
        association_fee = AssociationFee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssociationFee.any_instance.stub(:save).and_return(false)
        put :update, {:id => association_fee.to_param, :association_fee => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested association_fee" do
      association_fee = AssociationFee.create! valid_attributes
      expect {
        delete :destroy, {:id => association_fee.to_param}, valid_session
      }.to change(AssociationFee, :count).by(-1)
    end

    it "redirects to the association_fees list" do
      association_fee = AssociationFee.create! valid_attributes
      delete :destroy, {:id => association_fee.to_param}, valid_session
      response.should redirect_to(association_fees_url)
    end
  end

end
