require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoachCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # CoachCategory. As you add validations to CoachCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoachCategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all coach_categories as @coach_categories" do
      coach_category = CoachCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coach_categories).should eq([coach_category])
    end
  end

  describe "GET show" do
    it "assigns the requested coach_category as @coach_category" do
      coach_category = CoachCategory.create! valid_attributes
      get :show, {:id => coach_category.to_param}, valid_session
      assigns(:coach_category).should eq(coach_category)
    end
  end

  describe "GET new" do
    it "assigns a new coach_category as @coach_category" do
      get :new, {}, valid_session
      assigns(:coach_category).should be_a_new(CoachCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested coach_category as @coach_category" do
      coach_category = CoachCategory.create! valid_attributes
      get :edit, {:id => coach_category.to_param}, valid_session
      assigns(:coach_category).should eq(coach_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CoachCategory" do
        expect {
          post :create, {:coach_category => valid_attributes}, valid_session
        }.to change(CoachCategory, :count).by(1)
      end

      it "assigns a newly created coach_category as @coach_category" do
        post :create, {:coach_category => valid_attributes}, valid_session
        assigns(:coach_category).should be_a(CoachCategory)
        assigns(:coach_category).should be_persisted
      end

      it "redirects to the created coach_category" do
        post :create, {:coach_category => valid_attributes}, valid_session
        response.should redirect_to(CoachCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coach_category as @coach_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoachCategory.any_instance.stub(:save).and_return(false)
        post :create, {:coach_category => { "name" => "invalid value" }}, valid_session
        assigns(:coach_category).should be_a_new(CoachCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoachCategory.any_instance.stub(:save).and_return(false)
        post :create, {:coach_category => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coach_category" do
        coach_category = CoachCategory.create! valid_attributes
        # Assuming there are no other coach_categories in the database, this
        # specifies that the CoachCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CoachCategory.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => coach_category.to_param, :coach_category => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested coach_category as @coach_category" do
        coach_category = CoachCategory.create! valid_attributes
        put :update, {:id => coach_category.to_param, :coach_category => valid_attributes}, valid_session
        assigns(:coach_category).should eq(coach_category)
      end

      it "redirects to the coach_category" do
        coach_category = CoachCategory.create! valid_attributes
        put :update, {:id => coach_category.to_param, :coach_category => valid_attributes}, valid_session
        response.should redirect_to(coach_category)
      end
    end

    describe "with invalid params" do
      it "assigns the coach_category as @coach_category" do
        coach_category = CoachCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoachCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => coach_category.to_param, :coach_category => { "name" => "invalid value" }}, valid_session
        assigns(:coach_category).should eq(coach_category)
      end

      it "re-renders the 'edit' template" do
        coach_category = CoachCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoachCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => coach_category.to_param, :coach_category => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coach_category" do
      coach_category = CoachCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => coach_category.to_param}, valid_session
      }.to change(CoachCategory, :count).by(-1)
    end

    it "redirects to the coach_categories list" do
      coach_category = CoachCategory.create! valid_attributes
      delete :destroy, {:id => coach_category.to_param}, valid_session
      response.should redirect_to(coach_categories_url)
    end
  end

end
