require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GraduationsController do

  # This should return the minimal set of attributes required to create a valid
  # Graduation. As you add validations to Graduation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GraduationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all graduations as @graduations" do
      graduation = Graduation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:graduations).should eq([graduation])
    end
  end

  describe "GET show" do
    it "assigns the requested graduation as @graduation" do
      graduation = Graduation.create! valid_attributes
      get :show, {:id => graduation.to_param}, valid_session
      assigns(:graduation).should eq(graduation)
    end
  end

  describe "GET new" do
    it "assigns a new graduation as @graduation" do
      get :new, {}, valid_session
      assigns(:graduation).should be_a_new(Graduation)
    end
  end

  describe "GET edit" do
    it "assigns the requested graduation as @graduation" do
      graduation = Graduation.create! valid_attributes
      get :edit, {:id => graduation.to_param}, valid_session
      assigns(:graduation).should eq(graduation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Graduation" do
        expect {
          post :create, {:graduation => valid_attributes}, valid_session
        }.to change(Graduation, :count).by(1)
      end

      it "assigns a newly created graduation as @graduation" do
        post :create, {:graduation => valid_attributes}, valid_session
        assigns(:graduation).should be_a(Graduation)
        assigns(:graduation).should be_persisted
      end

      it "redirects to the created graduation" do
        post :create, {:graduation => valid_attributes}, valid_session
        response.should redirect_to(Graduation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved graduation as @graduation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Graduation.any_instance.stub(:save).and_return(false)
        post :create, {:graduation => { "name" => "invalid value" }}, valid_session
        assigns(:graduation).should be_a_new(Graduation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Graduation.any_instance.stub(:save).and_return(false)
        post :create, {:graduation => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested graduation" do
        graduation = Graduation.create! valid_attributes
        # Assuming there are no other graduations in the database, this
        # specifies that the Graduation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Graduation.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => graduation.to_param, :graduation => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested graduation as @graduation" do
        graduation = Graduation.create! valid_attributes
        put :update, {:id => graduation.to_param, :graduation => valid_attributes}, valid_session
        assigns(:graduation).should eq(graduation)
      end

      it "redirects to the graduation" do
        graduation = Graduation.create! valid_attributes
        put :update, {:id => graduation.to_param, :graduation => valid_attributes}, valid_session
        response.should redirect_to(graduation)
      end
    end

    describe "with invalid params" do
      it "assigns the graduation as @graduation" do
        graduation = Graduation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Graduation.any_instance.stub(:save).and_return(false)
        put :update, {:id => graduation.to_param, :graduation => { "name" => "invalid value" }}, valid_session
        assigns(:graduation).should eq(graduation)
      end

      it "re-renders the 'edit' template" do
        graduation = Graduation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Graduation.any_instance.stub(:save).and_return(false)
        put :update, {:id => graduation.to_param, :graduation => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested graduation" do
      graduation = Graduation.create! valid_attributes
      expect {
        delete :destroy, {:id => graduation.to_param}, valid_session
      }.to change(Graduation, :count).by(-1)
    end

    it "redirects to the graduations list" do
      graduation = Graduation.create! valid_attributes
      delete :destroy, {:id => graduation.to_param}, valid_session
      response.should redirect_to(graduations_url)
    end
  end

end
