require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RefereeCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # RefereeCategory. As you add validations to RefereeCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RefereeCategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all referee_categories as @referee_categories" do
      referee_category = RefereeCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:referee_categories).should eq([referee_category])
    end
  end

  describe "GET show" do
    it "assigns the requested referee_category as @referee_category" do
      referee_category = RefereeCategory.create! valid_attributes
      get :show, {:id => referee_category.to_param}, valid_session
      assigns(:referee_category).should eq(referee_category)
    end
  end

  describe "GET new" do
    it "assigns a new referee_category as @referee_category" do
      get :new, {}, valid_session
      assigns(:referee_category).should be_a_new(RefereeCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested referee_category as @referee_category" do
      referee_category = RefereeCategory.create! valid_attributes
      get :edit, {:id => referee_category.to_param}, valid_session
      assigns(:referee_category).should eq(referee_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RefereeCategory" do
        expect {
          post :create, {:referee_category => valid_attributes}, valid_session
        }.to change(RefereeCategory, :count).by(1)
      end

      it "assigns a newly created referee_category as @referee_category" do
        post :create, {:referee_category => valid_attributes}, valid_session
        assigns(:referee_category).should be_a(RefereeCategory)
        assigns(:referee_category).should be_persisted
      end

      it "redirects to the created referee_category" do
        post :create, {:referee_category => valid_attributes}, valid_session
        response.should redirect_to(RefereeCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved referee_category as @referee_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        RefereeCategory.any_instance.stub(:save).and_return(false)
        post :create, {:referee_category => { "name" => "invalid value" }}, valid_session
        assigns(:referee_category).should be_a_new(RefereeCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RefereeCategory.any_instance.stub(:save).and_return(false)
        post :create, {:referee_category => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested referee_category" do
        referee_category = RefereeCategory.create! valid_attributes
        # Assuming there are no other referee_categories in the database, this
        # specifies that the RefereeCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RefereeCategory.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => referee_category.to_param, :referee_category => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested referee_category as @referee_category" do
        referee_category = RefereeCategory.create! valid_attributes
        put :update, {:id => referee_category.to_param, :referee_category => valid_attributes}, valid_session
        assigns(:referee_category).should eq(referee_category)
      end

      it "redirects to the referee_category" do
        referee_category = RefereeCategory.create! valid_attributes
        put :update, {:id => referee_category.to_param, :referee_category => valid_attributes}, valid_session
        response.should redirect_to(referee_category)
      end
    end

    describe "with invalid params" do
      it "assigns the referee_category as @referee_category" do
        referee_category = RefereeCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RefereeCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => referee_category.to_param, :referee_category => { "name" => "invalid value" }}, valid_session
        assigns(:referee_category).should eq(referee_category)
      end

      it "re-renders the 'edit' template" do
        referee_category = RefereeCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RefereeCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => referee_category.to_param, :referee_category => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested referee_category" do
      referee_category = RefereeCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => referee_category.to_param}, valid_session
      }.to change(RefereeCategory, :count).by(-1)
    end

    it "redirects to the referee_categories list" do
      referee_category = RefereeCategory.create! valid_attributes
      delete :destroy, {:id => referee_category.to_param}, valid_session
      response.should redirect_to(referee_categories_url)
    end
  end

end
